// proto/pingogate.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.5
// source: pingogate.proto

package pingogatepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Snapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint64                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"` // S1 占位;S2 扩展
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_pingogate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_pingogate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_pingogate_proto_rawDescGZIP(), []int{0}
}

func (x *Snapshot) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Snapshot) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint64                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_pingogate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_pingogate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_pingogate_proto_rawDescGZIP(), []int{1}
}

func (x *Ack) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Ack) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Ack) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 预留:增量推送(S2/S3 不实现)
type PushDeltaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromVersion   uint64                 `protobuf:"varint,1,opt,name=from_version,json=fromVersion,proto3" json:"from_version,omitempty"`
	ToVersion     uint64                 `protobuf:"varint,2,opt,name=to_version,json=toVersion,proto3" json:"to_version,omitempty"` // S2/S3 不填;转增量时扩展 added/modified/removed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushDeltaRequest) Reset() {
	*x = PushDeltaRequest{}
	mi := &file_pingogate_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushDeltaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushDeltaRequest) ProtoMessage() {}

func (x *PushDeltaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pingogate_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushDeltaRequest.ProtoReflect.Descriptor instead.
func (*PushDeltaRequest) Descriptor() ([]byte, []int) {
	return file_pingogate_proto_rawDescGZIP(), []int{2}
}

func (x *PushDeltaRequest) GetFromVersion() uint64 {
	if x != nil {
		return x.FromVersion
	}
	return 0
}

func (x *PushDeltaRequest) GetToVersion() uint64 {
	if x != nil {
		return x.ToVersion
	}
	return 0
}

type HeartbeatRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CurrentVersion uint64                 `protobuf:"varint,1,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"`
	Ready          bool                   `protobuf:"varint,2,opt,name=ready,proto3" json:"ready,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_pingogate_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pingogate_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_pingogate_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatRequest) GetCurrentVersion() uint64 {
	if x != nil {
		return x.CurrentVersion
	}
	return 0
}

func (x *HeartbeatRequest) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_pingogate_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pingogate_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_pingogate_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

type HealthRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CurrentVersion uint64                 `protobuf:"varint,1,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"` // Rust 报告当前快照 version
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_pingogate_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pingogate_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_pingogate_proto_rawDescGZIP(), []int{5}
}

func (x *HealthRequest) GetCurrentVersion() uint64 {
	if x != nil {
		return x.CurrentVersion
	}
	return 0
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ready         bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"` // Rust 是否 ready(收到首个全量快照后)
	Version       uint64                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_pingogate_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pingogate_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_pingogate_proto_rawDescGZIP(), []int{6}
}

func (x *HealthResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *HealthResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type EncryptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plaintext     []byte                 `protobuf:"bytes,1,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptRequest) Reset() {
	*x = EncryptRequest{}
	mi := &file_pingogate_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptRequest) ProtoMessage() {}

func (x *EncryptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pingogate_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptRequest.ProtoReflect.Descriptor instead.
func (*EncryptRequest) Descriptor() ([]byte, []int) {
	return file_pingogate_proto_rawDescGZIP(), []int{7}
}

func (x *EncryptRequest) GetPlaintext() []byte {
	if x != nil {
		return x.Plaintext
	}
	return nil
}

type EncryptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ciphertext    []byte                 `protobuf:"bytes,1,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptResponse) Reset() {
	*x = EncryptResponse{}
	mi := &file_pingogate_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptResponse) ProtoMessage() {}

func (x *EncryptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pingogate_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptResponse.ProtoReflect.Descriptor instead.
func (*EncryptResponse) Descriptor() ([]byte, []int) {
	return file_pingogate_proto_rawDescGZIP(), []int{8}
}

func (x *EncryptResponse) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

func (x *EncryptResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DecryptRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Ciphertext      []byte                 `protobuf:"bytes,1,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	RequesterUserId string                 `protobuf:"bytes,2,opt,name=requester_user_id,json=requesterUserId,proto3" json:"requester_user_id,omitempty"` // S3 双防线用
	KeyId           string                 `protobuf:"bytes,3,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Intent          string                 `protobuf:"bytes,4,opt,name=intent,proto3" json:"intent,omitempty"` // view_plaintext | hot_path_inject
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DecryptRequest) Reset() {
	*x = DecryptRequest{}
	mi := &file_pingogate_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecryptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptRequest) ProtoMessage() {}

func (x *DecryptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pingogate_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptRequest.ProtoReflect.Descriptor instead.
func (*DecryptRequest) Descriptor() ([]byte, []int) {
	return file_pingogate_proto_rawDescGZIP(), []int{9}
}

func (x *DecryptRequest) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

func (x *DecryptRequest) GetRequesterUserId() string {
	if x != nil {
		return x.RequesterUserId
	}
	return ""
}

func (x *DecryptRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *DecryptRequest) GetIntent() string {
	if x != nil {
		return x.Intent
	}
	return ""
}

type DecryptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plaintext     []byte                 `protobuf:"bytes,1,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecryptResponse) Reset() {
	*x = DecryptResponse{}
	mi := &file_pingogate_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecryptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptResponse) ProtoMessage() {}

func (x *DecryptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pingogate_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptResponse.ProtoReflect.Descriptor instead.
func (*DecryptResponse) Descriptor() ([]byte, []int) {
	return file_pingogate_proto_rawDescGZIP(), []int{10}
}

func (x *DecryptResponse) GetPlaintext() []byte {
	if x != nil {
		return x.Plaintext
	}
	return nil
}

func (x *DecryptResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UsageEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint64                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"` // S3 扩展为结构化 usage
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsageEvent) Reset() {
	*x = UsageEvent{}
	mi := &file_pingogate_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageEvent) ProtoMessage() {}

func (x *UsageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pingogate_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageEvent.ProtoReflect.Descriptor instead.
func (*UsageEvent) Descriptor() ([]byte, []int) {
	return file_pingogate_proto_rawDescGZIP(), []int{11}
}

func (x *UsageEvent) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *UsageEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_pingogate_proto protoreflect.FileDescriptor

const file_pingogate_proto_rawDesc = "" +
	"\n" +
	"\x0fpingogate.proto\x12\tpingogate\">\n" +
	"\bSnapshot\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"E\n" +
	"\x03Ack\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"T\n" +
	"\x10PushDeltaRequest\x12!\n" +
	"\ffrom_version\x18\x01 \x01(\x04R\vfromVersion\x12\x1d\n" +
	"\n" +
	"to_version\x18\x02 \x01(\x04R\ttoVersion\"Q\n" +
	"\x10HeartbeatRequest\x12'\n" +
	"\x0fcurrent_version\x18\x01 \x01(\x04R\x0ecurrentVersion\x12\x14\n" +
	"\x05ready\x18\x02 \x01(\bR\x05ready\"7\n" +
	"\x11HeartbeatResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\"8\n" +
	"\rHealthRequest\x12'\n" +
	"\x0fcurrent_version\x18\x01 \x01(\x04R\x0ecurrentVersion\"@\n" +
	"\x0eHealthResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x04R\aversion\".\n" +
	"\x0eEncryptRequest\x12\x1c\n" +
	"\tplaintext\x18\x01 \x01(\fR\tplaintext\"G\n" +
	"\x0fEncryptResponse\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x01 \x01(\fR\n" +
	"ciphertext\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x8b\x01\n" +
	"\x0eDecryptRequest\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x01 \x01(\fR\n" +
	"ciphertext\x12*\n" +
	"\x11requester_user_id\x18\x02 \x01(\tR\x0frequesterUserId\x12\x15\n" +
	"\x06key_id\x18\x03 \x01(\tR\x05keyId\x12\x16\n" +
	"\x06intent\x18\x04 \x01(\tR\x06intent\"E\n" +
	"\x0fDecryptResponse\x12\x1c\n" +
	"\tplaintext\x18\x01 \x01(\fR\tplaintext\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"@\n" +
	"\n" +
	"UsageEvent\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload2\xcc\x01\n" +
	"\x0fSnapshotService\x125\n" +
	"\fPushSnapshot\x12\x13.pingogate.Snapshot\x1a\x0e.pingogate.Ack(\x01\x12F\n" +
	"\tHeartbeat\x12\x1b.pingogate.HeartbeatRequest\x1a\x1c.pingogate.HeartbeatResponse\x12:\n" +
	"\tPushDelta\x12\x1b.pingogate.PushDeltaRequest\x1a\x0e.pingogate.Ack(\x012\x95\x01\n" +
	"\x0fKeyVaultService\x12@\n" +
	"\aEncrypt\x12\x19.pingogate.EncryptRequest\x1a\x1a.pingogate.EncryptResponse\x12@\n" +
	"\aDecrypt\x12\x19.pingogate.DecryptRequest\x1a\x1a.pingogate.DecryptResponse2F\n" +
	"\fUsageService\x126\n" +
	"\vReportUsage\x12\x15.pingogate.UsageEvent\x1a\x0e.pingogate.Ack(\x012M\n" +
	"\rHealthService\x12<\n" +
	"\x05Check\x12\x18.pingogate.HealthRequest\x1a\x19.pingogate.HealthResponseB?Z=github.com/whw23/pingogate/ctrl-go/internal/proto;pingogatepbb\x06proto3"

var (
	file_pingogate_proto_rawDescOnce sync.Once
	file_pingogate_proto_rawDescData []byte
)

func file_pingogate_proto_rawDescGZIP() []byte {
	file_pingogate_proto_rawDescOnce.Do(func() {
		file_pingogate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pingogate_proto_rawDesc), len(file_pingogate_proto_rawDesc)))
	})
	return file_pingogate_proto_rawDescData
}

var file_pingogate_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_pingogate_proto_goTypes = []any{
	(*Snapshot)(nil),          // 0: pingogate.Snapshot
	(*Ack)(nil),               // 1: pingogate.Ack
	(*PushDeltaRequest)(nil),  // 2: pingogate.PushDeltaRequest
	(*HeartbeatRequest)(nil),  // 3: pingogate.HeartbeatRequest
	(*HeartbeatResponse)(nil), // 4: pingogate.HeartbeatResponse
	(*HealthRequest)(nil),     // 5: pingogate.HealthRequest
	(*HealthResponse)(nil),    // 6: pingogate.HealthResponse
	(*EncryptRequest)(nil),    // 7: pingogate.EncryptRequest
	(*EncryptResponse)(nil),   // 8: pingogate.EncryptResponse
	(*DecryptRequest)(nil),    // 9: pingogate.DecryptRequest
	(*DecryptResponse)(nil),   // 10: pingogate.DecryptResponse
	(*UsageEvent)(nil),        // 11: pingogate.UsageEvent
}
var file_pingogate_proto_depIdxs = []int32{
	0,  // 0: pingogate.SnapshotService.PushSnapshot:input_type -> pingogate.Snapshot
	3,  // 1: pingogate.SnapshotService.Heartbeat:input_type -> pingogate.HeartbeatRequest
	2,  // 2: pingogate.SnapshotService.PushDelta:input_type -> pingogate.PushDeltaRequest
	7,  // 3: pingogate.KeyVaultService.Encrypt:input_type -> pingogate.EncryptRequest
	9,  // 4: pingogate.KeyVaultService.Decrypt:input_type -> pingogate.DecryptRequest
	11, // 5: pingogate.UsageService.ReportUsage:input_type -> pingogate.UsageEvent
	5,  // 6: pingogate.HealthService.Check:input_type -> pingogate.HealthRequest
	1,  // 7: pingogate.SnapshotService.PushSnapshot:output_type -> pingogate.Ack
	4,  // 8: pingogate.SnapshotService.Heartbeat:output_type -> pingogate.HeartbeatResponse
	1,  // 9: pingogate.SnapshotService.PushDelta:output_type -> pingogate.Ack
	8,  // 10: pingogate.KeyVaultService.Encrypt:output_type -> pingogate.EncryptResponse
	10, // 11: pingogate.KeyVaultService.Decrypt:output_type -> pingogate.DecryptResponse
	1,  // 12: pingogate.UsageService.ReportUsage:output_type -> pingogate.Ack
	6,  // 13: pingogate.HealthService.Check:output_type -> pingogate.HealthResponse
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_pingogate_proto_init() }
func file_pingogate_proto_init() {
	if File_pingogate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pingogate_proto_rawDesc), len(file_pingogate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_pingogate_proto_goTypes,
		DependencyIndexes: file_pingogate_proto_depIdxs,
		MessageInfos:      file_pingogate_proto_msgTypes,
	}.Build()
	File_pingogate_proto = out.File
	file_pingogate_proto_goTypes = nil
	file_pingogate_proto_depIdxs = nil
}
