// proto/pingogate.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.5
// source: pingogate.proto

package pingogatepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Snapshot struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Version       uint64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Providers     []*ProviderEntry        `protobuf:"bytes,2,rep,name=providers,proto3" json:"providers,omitempty"`
	Routes        []*RouteEntry           `protobuf:"bytes,3,rep,name=routes,proto3" json:"routes,omitempty"`
	VirtualKeys   []*VirtualKeyEntry      `protobuf:"bytes,4,rep,name=virtual_keys,json=virtualKeys,proto3" json:"virtual_keys,omitempty"` // S3 填充,S2 留空
	EncryptedKeys []*EncryptedProviderKey `protobuf:"bytes,5,rep,name=encrypted_keys,json=encryptedKeys,proto3" json:"encrypted_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_pingogate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_pingogate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_pingogate_proto_rawDescGZIP(), []int{0}
}

func (x *Snapshot) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Snapshot) GetProviders() []*ProviderEntry {
	if x != nil {
		return x.Providers
	}
	return nil
}

func (x *Snapshot) GetRoutes() []*RouteEntry {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *Snapshot) GetVirtualKeys() []*VirtualKeyEntry {
	if x != nil {
		return x.VirtualKeys
	}
	return nil
}

func (x *Snapshot) GetEncryptedKeys() []*EncryptedProviderKey {
	if x != nil {
		return x.EncryptedKeys
	}
	return nil
}

type ProviderEntry struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Name               string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind               string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"` // openai-compatible / anthropic / gemini
	BaseUrl            string                 `protobuf:"bytes,3,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	AuthMethod         string                 `protobuf:"bytes,4,opt,name=auth_method,json=authMethod,proto3" json:"auth_method,omitempty"`                  // bearer / api_key_header / query_key
	EncryptedKeyRef    string                 `protobuf:"bytes,5,opt,name=encrypted_key_ref,json=encryptedKeyRef,proto3" json:"encrypted_key_ref,omitempty"` // 引用 encrypted_keys 中的 id
	AnthropicVersion   string                 `protobuf:"bytes,6,opt,name=anthropic_version,json=anthropicVersion,proto3" json:"anthropic_version,omitempty"`
	CapabilityFamilies []string               `protobuf:"bytes,7,rep,name=capability_families,json=capabilityFamilies,proto3" json:"capability_families,omitempty"`
	TimeoutMs          *uint64                `protobuf:"varint,8,opt,name=timeout_ms,json=timeoutMs,proto3,oneof" json:"timeout_ms,omitempty"` // per-provider 超时覆盖 (issue 3)
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ProviderEntry) Reset() {
	*x = ProviderEntry{}
	mi := &file_pingogate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderEntry) ProtoMessage() {}

func (x *ProviderEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pingogate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderEntry.ProtoReflect.Descriptor instead.
func (*ProviderEntry) Descriptor() ([]byte, []int) {
	return file_pingogate_proto_rawDescGZIP(), []int{1}
}

func (x *ProviderEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProviderEntry) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ProviderEntry) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *ProviderEntry) GetAuthMethod() string {
	if x != nil {
		return x.AuthMethod
	}
	return ""
}

func (x *ProviderEntry) GetEncryptedKeyRef() string {
	if x != nil {
		return x.EncryptedKeyRef
	}
	return ""
}

func (x *ProviderEntry) GetAnthropicVersion() string {
	if x != nil {
		return x.AnthropicVersion
	}
	return ""
}

func (x *ProviderEntry) GetCapabilityFamilies() []string {
	if x != nil {
		return x.CapabilityFamilies
	}
	return nil
}

func (x *ProviderEntry) GetTimeoutMs() uint64 {
	if x != nil && x.TimeoutMs != nil {
		return *x.TimeoutMs
	}
	return 0
}

type RouteEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alias         string                 `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	UpstreamModel string                 `protobuf:"bytes,3,opt,name=upstream_model,json=upstreamModel,proto3" json:"upstream_model,omitempty"`
	UpstreamPath  *string                `protobuf:"bytes,4,opt,name=upstream_path,json=upstreamPath,proto3,oneof" json:"upstream_path,omitempty"` // 上游路径模板,支持 {model} 占位符 (issue 2)
	AuthMethod    *string                `protobuf:"bytes,5,opt,name=auth_method,json=authMethod,proto3,oneof" json:"auth_method,omitempty"`       // per-route auth 覆盖 (issue 1)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteEntry) Reset() {
	*x = RouteEntry{}
	mi := &file_pingogate_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteEntry) ProtoMessage() {}

func (x *RouteEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pingogate_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteEntry.ProtoReflect.Descriptor instead.
func (*RouteEntry) Descriptor() ([]byte, []int) {
	return file_pingogate_proto_rawDescGZIP(), []int{2}
}

func (x *RouteEntry) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *RouteEntry) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *RouteEntry) GetUpstreamModel() string {
	if x != nil {
		return x.UpstreamModel
	}
	return ""
}

func (x *RouteEntry) GetUpstreamPath() string {
	if x != nil && x.UpstreamPath != nil {
		return *x.UpstreamPath
	}
	return ""
}

func (x *RouteEntry) GetAuthMethod() string {
	if x != nil && x.AuthMethod != nil {
		return *x.AuthMethod
	}
	return ""
}

type EncryptedProviderKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ciphertext    []byte                 `protobuf:"bytes,2,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	OwnerUserId   string                 `protobuf:"bytes,3,opt,name=owner_user_id,json=ownerUserId,proto3" json:"owner_user_id,omitempty"` // S3 双防线用
	CreatedBy     string                 `protobuf:"bytes,4,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptedProviderKey) Reset() {
	*x = EncryptedProviderKey{}
	mi := &file_pingogate_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedProviderKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedProviderKey) ProtoMessage() {}

func (x *EncryptedProviderKey) ProtoReflect() protoreflect.Message {
	mi := &file_pingogate_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedProviderKey.ProtoReflect.Descriptor instead.
func (*EncryptedProviderKey) Descriptor() ([]byte, []int) {
	return file_pingogate_proto_rawDescGZIP(), []int{3}
}

func (x *EncryptedProviderKey) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EncryptedProviderKey) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

func (x *EncryptedProviderKey) GetOwnerUserId() string {
	if x != nil {
		return x.OwnerUserId
	}
	return ""
}

func (x *EncryptedProviderKey) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

type VirtualKeyEntry struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TokenHash        string                 `protobuf:"bytes,2,opt,name=token_hash,json=tokenHash,proto3" json:"token_hash,omitempty"` // bcrypt 或 SHA-256 hash
	OwnerUserId      string                 `protobuf:"bytes,3,opt,name=owner_user_id,json=ownerUserId,proto3" json:"owner_user_id,omitempty"`
	ProviderKeyId    string                 `protobuf:"bytes,4,opt,name=provider_key_id,json=providerKeyId,proto3" json:"provider_key_id,omitempty"` // 引用 encrypted_keys 的 key_id
	AllowedModels    []string               `protobuf:"bytes,5,rep,name=allowed_models,json=allowedModels,proto3" json:"allowed_models,omitempty"`
	AllowedProviders []string               `protobuf:"bytes,6,rep,name=allowed_providers,json=allowedProviders,proto3" json:"allowed_providers,omitempty"`
	ExpiresAt        int64                  `protobuf:"varint,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`                // unix ts,0 = 不过期
	MaxConcurrency   int32                  `protobuf:"varint,8,opt,name=max_concurrency,json=maxConcurrency,proto3" json:"max_concurrency,omitempty"` // 并发配额,0 = 不限
	Enabled          bool                   `protobuf:"varint,9,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VirtualKeyEntry) Reset() {
	*x = VirtualKeyEntry{}
	mi := &file_pingogate_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualKeyEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualKeyEntry) ProtoMessage() {}

func (x *VirtualKeyEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pingogate_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualKeyEntry.ProtoReflect.Descriptor instead.
func (*VirtualKeyEntry) Descriptor() ([]byte, []int) {
	return file_pingogate_proto_rawDescGZIP(), []int{4}
}

func (x *VirtualKeyEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VirtualKeyEntry) GetTokenHash() string {
	if x != nil {
		return x.TokenHash
	}
	return ""
}

func (x *VirtualKeyEntry) GetOwnerUserId() string {
	if x != nil {
		return x.OwnerUserId
	}
	return ""
}

func (x *VirtualKeyEntry) GetProviderKeyId() string {
	if x != nil {
		return x.ProviderKeyId
	}
	return ""
}

func (x *VirtualKeyEntry) GetAllowedModels() []string {
	if x != nil {
		return x.AllowedModels
	}
	return nil
}

func (x *VirtualKeyEntry) GetAllowedProviders() []string {
	if x != nil {
		return x.AllowedProviders
	}
	return nil
}

func (x *VirtualKeyEntry) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *VirtualKeyEntry) GetMaxConcurrency() int32 {
	if x != nil {
		return x.MaxConcurrency
	}
	return 0
}

func (x *VirtualKeyEntry) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint64                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_pingogate_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_pingogate_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_pingogate_proto_rawDescGZIP(), []int{5}
}

func (x *Ack) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Ack) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Ack) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 预留:增量推送(S2/S3 不实现)
type PushDeltaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromVersion   uint64                 `protobuf:"varint,1,opt,name=from_version,json=fromVersion,proto3" json:"from_version,omitempty"`
	ToVersion     uint64                 `protobuf:"varint,2,opt,name=to_version,json=toVersion,proto3" json:"to_version,omitempty"` // S2/S3 不填;转增量时扩展 added/modified/removed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushDeltaRequest) Reset() {
	*x = PushDeltaRequest{}
	mi := &file_pingogate_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushDeltaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushDeltaRequest) ProtoMessage() {}

func (x *PushDeltaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pingogate_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushDeltaRequest.ProtoReflect.Descriptor instead.
func (*PushDeltaRequest) Descriptor() ([]byte, []int) {
	return file_pingogate_proto_rawDescGZIP(), []int{6}
}

func (x *PushDeltaRequest) GetFromVersion() uint64 {
	if x != nil {
		return x.FromVersion
	}
	return 0
}

func (x *PushDeltaRequest) GetToVersion() uint64 {
	if x != nil {
		return x.ToVersion
	}
	return 0
}

type HeartbeatRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CurrentVersion uint64                 `protobuf:"varint,1,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"`
	Ready          bool                   `protobuf:"varint,2,opt,name=ready,proto3" json:"ready,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_pingogate_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pingogate_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_pingogate_proto_rawDescGZIP(), []int{7}
}

func (x *HeartbeatRequest) GetCurrentVersion() uint64 {
	if x != nil {
		return x.CurrentVersion
	}
	return 0
}

func (x *HeartbeatRequest) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_pingogate_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pingogate_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_pingogate_proto_rawDescGZIP(), []int{8}
}

func (x *HeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

type HealthRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CurrentVersion uint64                 `protobuf:"varint,1,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"` // Rust 报告当前快照 version
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_pingogate_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pingogate_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_pingogate_proto_rawDescGZIP(), []int{9}
}

func (x *HealthRequest) GetCurrentVersion() uint64 {
	if x != nil {
		return x.CurrentVersion
	}
	return 0
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ready         bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"` // Rust 是否 ready(收到首个全量快照后)
	Version       uint64                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_pingogate_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pingogate_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_pingogate_proto_rawDescGZIP(), []int{10}
}

func (x *HealthResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *HealthResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type EncryptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plaintext     []byte                 `protobuf:"bytes,1,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptRequest) Reset() {
	*x = EncryptRequest{}
	mi := &file_pingogate_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptRequest) ProtoMessage() {}

func (x *EncryptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pingogate_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptRequest.ProtoReflect.Descriptor instead.
func (*EncryptRequest) Descriptor() ([]byte, []int) {
	return file_pingogate_proto_rawDescGZIP(), []int{11}
}

func (x *EncryptRequest) GetPlaintext() []byte {
	if x != nil {
		return x.Plaintext
	}
	return nil
}

type EncryptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ciphertext    []byte                 `protobuf:"bytes,1,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptResponse) Reset() {
	*x = EncryptResponse{}
	mi := &file_pingogate_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptResponse) ProtoMessage() {}

func (x *EncryptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pingogate_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptResponse.ProtoReflect.Descriptor instead.
func (*EncryptResponse) Descriptor() ([]byte, []int) {
	return file_pingogate_proto_rawDescGZIP(), []int{12}
}

func (x *EncryptResponse) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

func (x *EncryptResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DecryptRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Ciphertext      []byte                 `protobuf:"bytes,1,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	RequesterUserId string                 `protobuf:"bytes,2,opt,name=requester_user_id,json=requesterUserId,proto3" json:"requester_user_id,omitempty"` // S3 双防线用
	KeyId           string                 `protobuf:"bytes,3,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Intent          string                 `protobuf:"bytes,4,opt,name=intent,proto3" json:"intent,omitempty"` // view_plaintext | hot_path_inject
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DecryptRequest) Reset() {
	*x = DecryptRequest{}
	mi := &file_pingogate_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecryptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptRequest) ProtoMessage() {}

func (x *DecryptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pingogate_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptRequest.ProtoReflect.Descriptor instead.
func (*DecryptRequest) Descriptor() ([]byte, []int) {
	return file_pingogate_proto_rawDescGZIP(), []int{13}
}

func (x *DecryptRequest) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

func (x *DecryptRequest) GetRequesterUserId() string {
	if x != nil {
		return x.RequesterUserId
	}
	return ""
}

func (x *DecryptRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *DecryptRequest) GetIntent() string {
	if x != nil {
		return x.Intent
	}
	return ""
}

type DecryptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plaintext     []byte                 `protobuf:"bytes,1,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecryptResponse) Reset() {
	*x = DecryptResponse{}
	mi := &file_pingogate_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecryptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptResponse) ProtoMessage() {}

func (x *DecryptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pingogate_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptResponse.ProtoReflect.Descriptor instead.
func (*DecryptResponse) Descriptor() ([]byte, []int) {
	return file_pingogate_proto_rawDescGZIP(), []int{14}
}

func (x *DecryptResponse) GetPlaintext() []byte {
	if x != nil {
		return x.Plaintext
	}
	return nil
}

func (x *DecryptResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UsageEvent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Version          uint64                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	VirtualKeyId     string                 `protobuf:"bytes,2,opt,name=virtual_key_id,json=virtualKeyId,proto3" json:"virtual_key_id,omitempty"`
	OwnerUserId      string                 `protobuf:"bytes,3,opt,name=owner_user_id,json=ownerUserId,proto3" json:"owner_user_id,omitempty"`
	Provider         string                 `protobuf:"bytes,4,opt,name=provider,proto3" json:"provider,omitempty"`
	Model            string                 `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	InputTokens      int64                  `protobuf:"varint,6,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens     int64                  `protobuf:"varint,7,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	ReasoningTokens  int64                  `protobuf:"varint,8,opt,name=reasoning_tokens,json=reasoningTokens,proto3" json:"reasoning_tokens,omitempty"`
	CacheReadTokens  int64                  `protobuf:"varint,9,opt,name=cache_read_tokens,json=cacheReadTokens,proto3" json:"cache_read_tokens,omitempty"`
	CacheWriteTokens int64                  `protobuf:"varint,10,opt,name=cache_write_tokens,json=cacheWriteTokens,proto3" json:"cache_write_tokens,omitempty"`
	Success          bool                   `protobuf:"varint,11,opt,name=success,proto3" json:"success,omitempty"`
	LatencyMs        int64                  `protobuf:"varint,12,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	NeedsEstimate    bool                   `protobuf:"varint,13,opt,name=needs_estimate,json=needsEstimate,proto3" json:"needs_estimate,omitempty"` // true = 无 usage,Go 估算(Rust 推 body)
	BodyRef          []byte                 `protobuf:"bytes,14,opt,name=body_ref,json=bodyRef,proto3" json:"body_ref,omitempty"`                    // needs_estimate=true 时的 body 引用/内容
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UsageEvent) Reset() {
	*x = UsageEvent{}
	mi := &file_pingogate_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageEvent) ProtoMessage() {}

func (x *UsageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pingogate_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageEvent.ProtoReflect.Descriptor instead.
func (*UsageEvent) Descriptor() ([]byte, []int) {
	return file_pingogate_proto_rawDescGZIP(), []int{15}
}

func (x *UsageEvent) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *UsageEvent) GetVirtualKeyId() string {
	if x != nil {
		return x.VirtualKeyId
	}
	return ""
}

func (x *UsageEvent) GetOwnerUserId() string {
	if x != nil {
		return x.OwnerUserId
	}
	return ""
}

func (x *UsageEvent) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *UsageEvent) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *UsageEvent) GetInputTokens() int64 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *UsageEvent) GetOutputTokens() int64 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *UsageEvent) GetReasoningTokens() int64 {
	if x != nil {
		return x.ReasoningTokens
	}
	return 0
}

func (x *UsageEvent) GetCacheReadTokens() int64 {
	if x != nil {
		return x.CacheReadTokens
	}
	return 0
}

func (x *UsageEvent) GetCacheWriteTokens() int64 {
	if x != nil {
		return x.CacheWriteTokens
	}
	return 0
}

func (x *UsageEvent) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UsageEvent) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *UsageEvent) GetNeedsEstimate() bool {
	if x != nil {
		return x.NeedsEstimate
	}
	return false
}

func (x *UsageEvent) GetBodyRef() []byte {
	if x != nil {
		return x.BodyRef
	}
	return nil
}

var File_pingogate_proto protoreflect.FileDescriptor

const file_pingogate_proto_rawDesc = "" +
	"\n" +
	"\x0fpingogate.proto\x12\tpingogate\"\x92\x02\n" +
	"\bSnapshot\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x126\n" +
	"\tproviders\x18\x02 \x03(\v2\x18.pingogate.ProviderEntryR\tproviders\x12-\n" +
	"\x06routes\x18\x03 \x03(\v2\x15.pingogate.RouteEntryR\x06routes\x12=\n" +
	"\fvirtual_keys\x18\x04 \x03(\v2\x1a.pingogate.VirtualKeyEntryR\vvirtualKeys\x12F\n" +
	"\x0eencrypted_keys\x18\x05 \x03(\v2\x1f.pingogate.EncryptedProviderKeyR\rencryptedKeys\"\xb0\x02\n" +
	"\rProviderEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x19\n" +
	"\bbase_url\x18\x03 \x01(\tR\abaseUrl\x12\x1f\n" +
	"\vauth_method\x18\x04 \x01(\tR\n" +
	"authMethod\x12*\n" +
	"\x11encrypted_key_ref\x18\x05 \x01(\tR\x0fencryptedKeyRef\x12+\n" +
	"\x11anthropic_version\x18\x06 \x01(\tR\x10anthropicVersion\x12/\n" +
	"\x13capability_families\x18\a \x03(\tR\x12capabilityFamilies\x12\"\n" +
	"\n" +
	"timeout_ms\x18\b \x01(\x04H\x00R\ttimeoutMs\x88\x01\x01B\r\n" +
	"\v_timeout_ms\"\xd7\x01\n" +
	"\n" +
	"RouteEntry\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12%\n" +
	"\x0eupstream_model\x18\x03 \x01(\tR\rupstreamModel\x12(\n" +
	"\rupstream_path\x18\x04 \x01(\tH\x00R\fupstreamPath\x88\x01\x01\x12$\n" +
	"\vauth_method\x18\x05 \x01(\tH\x01R\n" +
	"authMethod\x88\x01\x01B\x10\n" +
	"\x0e_upstream_pathB\x0e\n" +
	"\f_auth_method\"\x89\x01\n" +
	"\x14EncryptedProviderKey\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x02 \x01(\fR\n" +
	"ciphertext\x12\"\n" +
	"\rowner_user_id\x18\x03 \x01(\tR\vownerUserId\x12\x1d\n" +
	"\n" +
	"created_by\x18\x04 \x01(\tR\tcreatedBy\"\xc2\x02\n" +
	"\x0fVirtualKeyEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"token_hash\x18\x02 \x01(\tR\ttokenHash\x12\"\n" +
	"\rowner_user_id\x18\x03 \x01(\tR\vownerUserId\x12&\n" +
	"\x0fprovider_key_id\x18\x04 \x01(\tR\rproviderKeyId\x12%\n" +
	"\x0eallowed_models\x18\x05 \x03(\tR\rallowedModels\x12+\n" +
	"\x11allowed_providers\x18\x06 \x03(\tR\x10allowedProviders\x12\x1d\n" +
	"\n" +
	"expires_at\x18\a \x01(\x03R\texpiresAt\x12'\n" +
	"\x0fmax_concurrency\x18\b \x01(\x05R\x0emaxConcurrency\x12\x18\n" +
	"\aenabled\x18\t \x01(\bR\aenabled\"E\n" +
	"\x03Ack\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"T\n" +
	"\x10PushDeltaRequest\x12!\n" +
	"\ffrom_version\x18\x01 \x01(\x04R\vfromVersion\x12\x1d\n" +
	"\n" +
	"to_version\x18\x02 \x01(\x04R\ttoVersion\"Q\n" +
	"\x10HeartbeatRequest\x12'\n" +
	"\x0fcurrent_version\x18\x01 \x01(\x04R\x0ecurrentVersion\x12\x14\n" +
	"\x05ready\x18\x02 \x01(\bR\x05ready\"7\n" +
	"\x11HeartbeatResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\"8\n" +
	"\rHealthRequest\x12'\n" +
	"\x0fcurrent_version\x18\x01 \x01(\x04R\x0ecurrentVersion\"@\n" +
	"\x0eHealthResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x04R\aversion\".\n" +
	"\x0eEncryptRequest\x12\x1c\n" +
	"\tplaintext\x18\x01 \x01(\fR\tplaintext\"G\n" +
	"\x0fEncryptResponse\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x01 \x01(\fR\n" +
	"ciphertext\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x8b\x01\n" +
	"\x0eDecryptRequest\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x01 \x01(\fR\n" +
	"ciphertext\x12*\n" +
	"\x11requester_user_id\x18\x02 \x01(\tR\x0frequesterUserId\x12\x15\n" +
	"\x06key_id\x18\x03 \x01(\tR\x05keyId\x12\x16\n" +
	"\x06intent\x18\x04 \x01(\tR\x06intent\"E\n" +
	"\x0fDecryptResponse\x12\x1c\n" +
	"\tplaintext\x18\x01 \x01(\fR\tplaintext\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xea\x03\n" +
	"\n" +
	"UsageEvent\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x12$\n" +
	"\x0evirtual_key_id\x18\x02 \x01(\tR\fvirtualKeyId\x12\"\n" +
	"\rowner_user_id\x18\x03 \x01(\tR\vownerUserId\x12\x1a\n" +
	"\bprovider\x18\x04 \x01(\tR\bprovider\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\x12!\n" +
	"\finput_tokens\x18\x06 \x01(\x03R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\a \x01(\x03R\foutputTokens\x12)\n" +
	"\x10reasoning_tokens\x18\b \x01(\x03R\x0freasoningTokens\x12*\n" +
	"\x11cache_read_tokens\x18\t \x01(\x03R\x0fcacheReadTokens\x12,\n" +
	"\x12cache_write_tokens\x18\n" +
	" \x01(\x03R\x10cacheWriteTokens\x12\x18\n" +
	"\asuccess\x18\v \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\f \x01(\x03R\tlatencyMs\x12%\n" +
	"\x0eneeds_estimate\x18\r \x01(\bR\rneedsEstimate\x12\x19\n" +
	"\bbody_ref\x18\x0e \x01(\fR\abodyRef2\xcc\x01\n" +
	"\x0fSnapshotService\x125\n" +
	"\fPushSnapshot\x12\x13.pingogate.Snapshot\x1a\x0e.pingogate.Ack(\x01\x12F\n" +
	"\tHeartbeat\x12\x1b.pingogate.HeartbeatRequest\x1a\x1c.pingogate.HeartbeatResponse\x12:\n" +
	"\tPushDelta\x12\x1b.pingogate.PushDeltaRequest\x1a\x0e.pingogate.Ack(\x012\x95\x01\n" +
	"\x0fKeyVaultService\x12@\n" +
	"\aEncrypt\x12\x19.pingogate.EncryptRequest\x1a\x1a.pingogate.EncryptResponse\x12@\n" +
	"\aDecrypt\x12\x19.pingogate.DecryptRequest\x1a\x1a.pingogate.DecryptResponse2F\n" +
	"\fUsageService\x126\n" +
	"\vReportUsage\x12\x15.pingogate.UsageEvent\x1a\x0e.pingogate.Ack(\x012M\n" +
	"\rHealthService\x12<\n" +
	"\x05Check\x12\x18.pingogate.HealthRequest\x1a\x19.pingogate.HealthResponseB?Z=github.com/whw23/pingogate/ctrl-go/internal/proto;pingogatepbb\x06proto3"

var (
	file_pingogate_proto_rawDescOnce sync.Once
	file_pingogate_proto_rawDescData []byte
)

func file_pingogate_proto_rawDescGZIP() []byte {
	file_pingogate_proto_rawDescOnce.Do(func() {
		file_pingogate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pingogate_proto_rawDesc), len(file_pingogate_proto_rawDesc)))
	})
	return file_pingogate_proto_rawDescData
}

var file_pingogate_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_pingogate_proto_goTypes = []any{
	(*Snapshot)(nil),             // 0: pingogate.Snapshot
	(*ProviderEntry)(nil),        // 1: pingogate.ProviderEntry
	(*RouteEntry)(nil),           // 2: pingogate.RouteEntry
	(*EncryptedProviderKey)(nil), // 3: pingogate.EncryptedProviderKey
	(*VirtualKeyEntry)(nil),      // 4: pingogate.VirtualKeyEntry
	(*Ack)(nil),                  // 5: pingogate.Ack
	(*PushDeltaRequest)(nil),     // 6: pingogate.PushDeltaRequest
	(*HeartbeatRequest)(nil),     // 7: pingogate.HeartbeatRequest
	(*HeartbeatResponse)(nil),    // 8: pingogate.HeartbeatResponse
	(*HealthRequest)(nil),        // 9: pingogate.HealthRequest
	(*HealthResponse)(nil),       // 10: pingogate.HealthResponse
	(*EncryptRequest)(nil),       // 11: pingogate.EncryptRequest
	(*EncryptResponse)(nil),      // 12: pingogate.EncryptResponse
	(*DecryptRequest)(nil),       // 13: pingogate.DecryptRequest
	(*DecryptResponse)(nil),      // 14: pingogate.DecryptResponse
	(*UsageEvent)(nil),           // 15: pingogate.UsageEvent
}
var file_pingogate_proto_depIdxs = []int32{
	1,  // 0: pingogate.Snapshot.providers:type_name -> pingogate.ProviderEntry
	2,  // 1: pingogate.Snapshot.routes:type_name -> pingogate.RouteEntry
	4,  // 2: pingogate.Snapshot.virtual_keys:type_name -> pingogate.VirtualKeyEntry
	3,  // 3: pingogate.Snapshot.encrypted_keys:type_name -> pingogate.EncryptedProviderKey
	0,  // 4: pingogate.SnapshotService.PushSnapshot:input_type -> pingogate.Snapshot
	7,  // 5: pingogate.SnapshotService.Heartbeat:input_type -> pingogate.HeartbeatRequest
	6,  // 6: pingogate.SnapshotService.PushDelta:input_type -> pingogate.PushDeltaRequest
	11, // 7: pingogate.KeyVaultService.Encrypt:input_type -> pingogate.EncryptRequest
	13, // 8: pingogate.KeyVaultService.Decrypt:input_type -> pingogate.DecryptRequest
	15, // 9: pingogate.UsageService.ReportUsage:input_type -> pingogate.UsageEvent
	9,  // 10: pingogate.HealthService.Check:input_type -> pingogate.HealthRequest
	5,  // 11: pingogate.SnapshotService.PushSnapshot:output_type -> pingogate.Ack
	8,  // 12: pingogate.SnapshotService.Heartbeat:output_type -> pingogate.HeartbeatResponse
	5,  // 13: pingogate.SnapshotService.PushDelta:output_type -> pingogate.Ack
	12, // 14: pingogate.KeyVaultService.Encrypt:output_type -> pingogate.EncryptResponse
	14, // 15: pingogate.KeyVaultService.Decrypt:output_type -> pingogate.DecryptResponse
	5,  // 16: pingogate.UsageService.ReportUsage:output_type -> pingogate.Ack
	10, // 17: pingogate.HealthService.Check:output_type -> pingogate.HealthResponse
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_pingogate_proto_init() }
func file_pingogate_proto_init() {
	if File_pingogate_proto != nil {
		return
	}
	file_pingogate_proto_msgTypes[1].OneofWrappers = []any{}
	file_pingogate_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pingogate_proto_rawDesc), len(file_pingogate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_pingogate_proto_goTypes,
		DependencyIndexes: file_pingogate_proto_depIdxs,
		MessageInfos:      file_pingogate_proto_msgTypes,
	}.Build()
	File_pingogate_proto = out.File
	file_pingogate_proto_goTypes = nil
	file_pingogate_proto_depIdxs = nil
}
