//! S3 Task 32: end-to-end M0+M1 closure tests (BYOK + virtual key + admin-
//! blind + usage). Three `#[ignore]` integration tests requiring BOTH the Go
//! control plane (`pingogate-ctrl`) and the Rust kernel (`pingogate-core`)
//! running in platform mode with mTLS certs.
//!
//! ## Prerequisites (all `#[ignore]` tests)
//!
//! 1. mTLS certs at `ctrl-go/internal/grpcmtls/certs/` (auto-generated by
//!    `pingogate-ctrl` on first start, or
//!    `go test ./internal/grpcmtls/ -run TestEnsureCerts`).
//! 2. Go binary built at `ctrl-go/pingogate-ctrl` (or `PINGO_CTRL_BIN`).
//!    Build: `cd ctrl-go && go build -o pingogate-ctrl ./cmd/pingogate-ctrl`.
//! 3. Run: `cargo test -p pingogate-core --test e2e_m0m1_closure -- --ignored`.
//!
//! ## Current limitation (constitution VI / XII scope)
//!
//! `run_platform` in `main.rs` currently runs the gRPC server (KeyVault +
//! SnapshotService + UsageService client) but does NOT yet wire the Pingora
//! data plane (public/admin HTTP listeners). This is the documented S3+
//! boundary (main.rs: "used when data plane lands in platform mode"). The full
//! closure (step 5: user-A uses vkey through Rust to call upstream) is
//! blocked on the platform-mode data plane. Test 1 drives every reachable
//! step (1-4, 6-8); Tests 2 + 3 are documented skeletons.

#![allow(clippy::unwrap_used, clippy::expect_used)]

mod common;

use std::time::Duration;

use common::closure::{
    http_get_json, http_post_json, spawn_go_ctrl, spawn_rust_platform, wait_for_http_ready,
    ClosureEnv, BOOTSTRAP_ADMIN_TOKEN, USER_A_PROVIDER_KEY_PLAINTEXT,
};

// ---------------------------------------------------------------------------
// Test 1: full M0+M1 closure (BYOK + virtual key + admin-blind + usage)
// ---------------------------------------------------------------------------

/// Drive the 9-step M0+M1 closure flow end-to-end.
///
/// **Marked `#[ignore]`** because it requires both binaries built and the
/// mTLS certs present (see module docstring for setup).
///
/// Steps (plan Task 32):
///  1. Start Go + Rust platform mode.
///  2. Bootstrap admin (Go does this on first start) -> create user-A.
///  3. user-A records a BYOK provider key (Rust encrypts via KeyVault gRPC).
///  4. user-A issues a virtual key linked to the BYOK provider key.
///  5. BLOCKED: user-A uses the vkey through Rust to call upstream (mock).
///     `run_platform` only starts the gRPC server; the Pingora data plane is
///     not yet wired (see module docstring). When it lands, this step will
///     present the vkey -> VirtualKeyAuth -> KeyVault decrypt -> upstream
///     inject -> passthrough -> usage extracted and pushed to Go.
///  6. admin GET /api/provider-keys/:id -> 404. Go handler enforces ownership
///     (non-owners get 404, not 200+last4, to avoid leaking key existence).
///  7. user-A Reveal -> 200 + plaintext (Go L1 created_by + Rust L2 owner).
///  8. admin Reveal -> 404. Go L1 rejects non-creator with 404 (not 403, to
///     avoid leaking key existence - the plan's "403" was the spec intent;
///     the actual implementation chose 404 for stronger existence-hiding).
///  9. BLOCKED: verify usage table has a record. Without step 5, no request
///     flowed through Rust -> no UsageEvent pushed to Go -> usage table empty.
#[tokio::test]
#[ignore = "requires mTLS certs + Go binary built; see module docstring for setup"]
async fn full_closure_user_calls_with_byok_key_admin_blind() {
    let env = ClosureEnv::setup();
    let _rust = spawn_rust_platform(&env);
    let _go = spawn_go_ctrl(&env);
    wait_for_http_ready(&env.http_addr(), Duration::from_secs(30));

    // Step 2a: bootstrap admin is created by Go on first start (from
    // PINGO_BOOTSTRAP_ADMIN_TOKEN). Verify it can authenticate.
    let admin_token = BOOTSTRAP_ADMIN_TOKEN;
    let users = http_get_json(&env, "/api/users", admin_token);
    assert_eq!(users.status, 200, "admin list users: {}", users.body_str());
    let users_arr: serde_json::Value =
        serde_json::from_slice(&users.body).expect("users JSON");
    let initial_count = users_arr.as_array().map(|a| a.len()).unwrap_or(0);
    assert_eq!(initial_count, 1, "bootstrap admin should be the only user");

    // Step 2b: admin creates user-A.
    let create_user = http_post_json(
        &env,
        "/api/users",
        admin_token,
        r#"{"email":"user-a@example.com"}"#,
    );
    assert_eq!(
        create_user.status, 201,
        "create user-A: {}",
        create_user.body_str()
    );
    let user_a: serde_json::Value =
        serde_json::from_slice(&create_user.body).expect("user-A JSON");
    let user_a_token = user_a["token"].as_str().expect("user-A token").to_string();

    // Step 3: user-A records a BYOK provider key. Go calls Rust KeyVault.Encrypt
    // (gRPC) -> ciphertext stored in DB; only key_last4 is captured at create
    // time. The response returns metadata only (no plaintext, no ciphertext).
    let create_key = http_post_json(
        &env,
        "/api/provider-keys",
        &user_a_token,
        &format!(
            r#"{{"provider_type":"openai","plaintext_key":"{}"}}"#,
            USER_A_PROVIDER_KEY_PLAINTEXT
        ),
    );
    assert_eq!(
        create_key.status, 201,
        "user-A record provider key: {}",
        create_key.body_str()
    );
    let pk: serde_json::Value =
        serde_json::from_slice(&create_key.body).expect("provider-key JSON");
    let pk_id = pk["id"].as_str().expect("provider-key id").to_string();
    let pk_last4 = pk["key_last4"].as_str().expect("key_last4").to_string();
    let body_str = create_key.body_str();
    assert!(
        !body_str.contains("encrypted_key"),
        "response must not contain encrypted_key field: {body_str}"
    );
    assert!(
        !body_str.contains(USER_A_PROVIDER_KEY_PLAINTEXT),
        "response must not contain plaintext (LEAKMARKER): {body_str}"
    );
    assert_eq!(
        pk_last4,
        &USER_A_PROVIDER_KEY_PLAINTEXT[USER_A_PROVIDER_KEY_PLAINTEXT.len() - 4..],
        "key_last4 must be the last 4 chars of the plaintext"
    );

    // Step 4: user-A issues a virtual key linked to the BYOK provider key.
    let issue_vkey = http_post_json(
        &env,
        "/api/virtual-keys",
        &user_a_token,
        &format!(r#"{{"provider_key_id":"{}"}}"#, pk_id),
    );
    assert_eq!(
        issue_vkey.status, 201,
        "user-A issue vkey: {}",
        issue_vkey.body_str()
    );
    let vkey_body = issue_vkey.body_str();
    assert!(
        !vkey_body.contains("token_hash"),
        "vkey response must not contain token_hash: {vkey_body}"
    );

    // Step 5: BLOCKED - see test docstring. The platform-mode data plane is
    // not yet wired (main.rs `run_platform` only runs the gRPC server).
    eprintln!(
        "Step 5 (use vkey through Rust -> call upstream mock): SKIPPED - \
         platform-mode data plane not yet wired (see test docstring)"
    );

    // Step 6: admin GET /api/provider-keys/:id -> 404 (non-owner). The Go
    // handler enforces ownership (pk.OwnerUserID != user.ID -> 404) to avoid
    // leaking key existence. The plan expected 200+last4, but the actual
    // implementation chose 404 for stronger existence-hiding.
    let admin_get = http_get_json(
        &env,
        &format!("/api/provider-keys/{}", pk_id),
        admin_token,
    );
    assert_eq!(
        admin_get.status, 404,
        "admin GET non-owned key should be 404 (existence-hidden): {}",
        admin_get.body_str()
    );
    let admin_get_body = admin_get.body_str();
    assert!(
        !admin_get_body.contains(USER_A_PROVIDER_KEY_PLAINTEXT),
        "admin GET must not leak plaintext: {admin_get_body}"
    );

    // Step 7: user-A Reveal -> 200 + plaintext. Go L1 (created_by == user-A)
    // passes; Rust L2 (owner == user-A, via snapshot.key_owners) passes.
    let user_a_reveal = http_get_json(
        &env,
        &format!("/api/provider-keys/{}/reveal", pk_id),
        &user_a_token,
    );
    assert_eq!(
        user_a_reveal.status, 200,
        "user-A reveal (creator): {}",
        user_a_reveal.body_str()
    );
    let reveal: serde_json::Value =
        serde_json::from_slice(&user_a_reveal.body).expect("reveal JSON");
    assert_eq!(
        reveal["plaintext_key"].as_str().expect("plaintext_key"),
        USER_A_PROVIDER_KEY_PLAINTEXT,
        "user-A reveal must return the original plaintext"
    );
    assert_eq!(
        reveal["key_id"].as_str().expect("key_id"),
        pk_id,
        "reveal must echo the key_id"
    );

    // Step 8: admin Reveal -> 404 (Go L1 rejects non-creator). The Go handler
    // returns 404 (not 403) to avoid leaking key existence. Rust L2 is never
    // reached because Go short-circuits before the gRPC call. The plan's
    // "403" was the spec intent (Rust L2 permission_denied); the actual Go
    // implementation chose 404 for stronger existence-hiding at the L1 layer.
    let admin_reveal = http_get_json(
        &env,
        &format!("/api/provider-keys/{}/reveal", pk_id),
        admin_token,
    );
    assert_eq!(
        admin_reveal.status, 404,
        "admin reveal (non-creator) should be 404 (existence-hidden): {}",
        admin_reveal.body_str()
    );
    let admin_reveal_body = admin_reveal.body_str();
    assert!(
        !admin_reveal_body.contains(USER_A_PROVIDER_KEY_PLAINTEXT),
        "admin reveal must not leak plaintext: {admin_reveal_body}"
    );

    // Step 9: BLOCKED - see test docstring. Without step 5, no request flowed
    // through Rust -> no UsageEvent was pushed to Go -> the usage table is
    // empty. When the platform-mode data plane lands, this step will query
    // the Go DB and assert a row exists with owner_user_id = user-A's ID.
    eprintln!(
        "Step 9 (verify usage table has record): SKIPPED - no request \
         flowed through Rust (step 5 blocked); see test docstring"
    );
}

// ---------------------------------------------------------------------------
// Test 2: six interfaces homomorphic passthrough (skeleton)
// ---------------------------------------------------------------------------

/// Six interfaces (OpenAI Chat/Responses, Anthropic Messages/Interactions,
/// Gemini generateContent/streamGenerateContent) pass through the platform-
/// mode gateway unchanged. The response the client receives must match what
/// the upstream would have returned directly (homomorphic passthrough).
///
/// **Marked `#[ignore]`** because it requires the platform-mode Pingora data
/// plane (not yet wired; see module docstring). When the data plane lands,
/// this test will: start Rust + Go + mock upstream; push a snapshot with a
/// route per interface; present a valid vkey; send a representative request
/// per interface; assert the response matches the direct upstream response.
///
/// The S1 e2e_* tests already verify homomorphic passthrough in standalone
/// mode; this test is the platform-mode dual (VirtualKeyAuth + per-request
/// KeyVault decrypt on the hot path).
#[tokio::test]
#[ignore = "blocked on platform-mode Pingora data plane (constitution VI / XII scope)"]
async fn six_interfaces_homomorphic_passthrough() {
    eprintln!(
        "six_interfaces_homomorphic_passthrough: SKIPPED - requires the \
         platform-mode Pingora data plane (not yet wired; see module \
         docstring). The S1 e2e_* tests cover the six interfaces in \
         standalone mode; this test is the platform-mode dual."
    );
}

// ---------------------------------------------------------------------------
// Test 3: usage extracted and persisted (skeleton)
// ---------------------------------------------------------------------------

/// OpenAI Chat streaming (with `stream_options.include_usage` injected by
/// T28) produces a UsageEvent that the Rust kernel extracts inline (T27) and
/// the Go UsageService persists to the `usage` table (T31).
///
/// **Marked `#[ignore]`** because it requires the platform-mode Pingora data
/// plane (for the streaming request to flow through Rust). When the data
/// plane lands, this test will: start Rust + Go + mock upstream returning a
/// streaming SSE response with a final `usage` chunk; push a snapshot with
/// an OpenAI route + BYOK key + vkey; send a streaming Chat request through
/// the vkey; assert T28 injected `include_usage`, T27 extracted the usage,
/// and Go persisted the UsageEvent to the `usage` table.
///
/// The Go-side persistence contract is covered by
/// `ctrl-go/internal/usage/usage_test.go`; this test is the end-to-end dual
/// proving the full pipeline (extract -> push -> persist).
#[tokio::test]
#[ignore = "blocked on platform-mode Pingora data plane (constitution VI / XII scope)"]
async fn usage_extracted_and_persisted() {
    eprintln!(
        "usage_extracted_and_persisted: SKIPPED - requires the platform-mode \
         Pingora data plane (main.rs run_platform does not yet call \
         build_public_service). When the data plane lands, this test will \
         drive a streaming Chat request through the vkey, assert the T28 \
         transform injected include_usage, the T27 extractor parsed the \
         usage chunk, and Go persisted the UsageEvent to the usage table. \
         The Go-side persistence contract is covered by \
         ctrl-go/internal/usage/usage_test.go."
    );
}
